image: mcr.microsoft.com/dotnet/sdk:6.0 

stages:          
  - build
  - test

before_script:
  - curl -fsSL https://deb.nodesource.com/setup_18.x | bash -
  - apt-get install -y nodejs
  - dotnet restore HotelApp.Server/HotelApp.Server.csproj
  - dotnet run --project HotelApp.Server/HotelApp.Server.csproj

build:
  stage: build
  script:
    - dotnet build HotelApp.Server/HotelApp.Server.csproj

test:
  stage: test
  script:
    - dotnet test HotelApp.Server.Tests/HotelApp.Server.Tests.csproj