# For more info on HTTP files go to https://aka.ms/vs/httpfile

GET http://localhost:5000/api/rooms/location/

###
POST http://localhost:5000/api/rooms
Content-Type: application/json

{
  "location": "PostTest",
  "features": ["postestfeature", "postestfeature2"],
  "isAvailable": true,
  "price": 100
}