# For more info on HTTP files go to https://aka.ms/vs/httpfile

GET http://localhost:5000/api/rooms/

###
GET http://localhost:5000/api/users
Accept: application/json

###
POST http://localhost:5000/api/rooms
Content-Type: application/json

{
  "location": "PostTest",
  "category": "Testcategory",
  "features": ["postestfeature", "postestfeature2"],
  "isAvailable": true,
  "price": 100
}

### Create New User
POST http://localhost:5000/api/users
Content-Type: application/json

{
  "userName": "Test",
  "passwordHash": "Test",
  "email": "testadmin@example.com",
  "phoneNumber": "test20451200321",
  "isAdmin": true
}

###
POST http://localhost:5000/api/bookings
Content-Type: application/json

{
  "RoomId": "123"
  "Name": "TestName",
  "Email": "test@test.com",
  "PhoneNumber": "123345457123",
  "StartDate": "2025-11-11",
  "EndDate": "2025-11-12",
  "Comments": "Testcomment"
}
###
POST http://localhost:5000/api/users/login
Content-Type: application/json

{
  "UserName": "Test",
  "Password": "Test"
}

###
POST http://localhost:5000/api/rooms
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1lIjoiVGVzdCIsImh0dHA6Ly9zY2hlbWFzLnhtbHNvYXAub3JnL3dzLzIwMDUvMDUvaWRlbnRpdHkvY2xhaW1zL25hbWVpZGVudGlmaWVyIjoiNjc0NWYzNWMwMDE2YTA3MTM2MDAyZGU1IiwiaHR0cDovL3NjaGVtYXMubWljcm9zb2Z0LmNvbS93cy8yMDA4LzA2L2lkZW50aXR5L2NsYWltcy9yb2xlIjoiQWRtaW4iLCJleHAiOjE3MzI2NDEyMjAsImlzcyI6IkhvdGVsQXBwIiwiYXVkIjoiSG90ZWxBcHBVc2VycyJ9.wtVFtF86fXD8aDILu18Ez6dNO9lFV5RfAhxGvxF8rVU
{
  "location": "Room 102",
  "category": "Twin",
  "features": ["postestfeature", "postestfeature2"],
  "IsAvailable": true,
  "price": 120
}

###
POST http://localhost:5000/api/rooms
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6sadsadHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1lIjoiVGVzdCIsImh0dHA6Ly9zY2hlbWFzLnhtbHNvYXAub3JnL3dzLzIwMDUvMDUvaWRlbnRpdHkvY2xhaW1zL25hbWVpZGVudGlmaWVyIjoiNjc0NWYzNWMwMDE2YTA3MTM2MDAyZGU1IiwiaHR0cDovL3NjaGVtYXMubWljcm9zb2Z0LmNvbS93cy8yMDA4LzA2L2lkZW50aXR5L2NsYWltcy9yb2xlIjoiQWRtaW4iLCJleHAiOjE3MzI2NDEyMjAsImlzcyI6IkhvdGVsQXBwIiwiYXVkIjoiSG90ZWxBcHBVc2VycyJ9.wtVFtF86fXD8aDILu18Ez6dNO9lFV5RfAhxGvxF8rVU
{
  "location": "Room 102",
  "category": "Singlel",
  "features": ["postestfeature", "postestfeature2"],
  "IsAvailable": true,
  "price": 100
}